<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<ApplicationIcon>akashi.ico</ApplicationIcon>
		<CETCompat>false</CETCompat>
		<AssemblyName>Universal Downloader</AssemblyName>
		<Version>1.0.1</Version>
		<AssemblyVersion>1.0.1.0</AssemblyVersion>
		<FileVersion>1.0.1.0</FileVersion>
		<Product>Universal Downloader</Product>
	</PropertyGroup>

	<ItemGroup>
		<Using Remove="System.Windows.Forms" />
		<Using Remove="System.Drawing" />
	</ItemGroup>

	<ItemGroup>
		<None Include="akashi.ico" CopyToOutputDirectory="PreserveNewest" />
		<Resource Include="akashi.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NAudio" Version="2.2.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
		<PackageReference Include="TagLibSharp" Version="2.3.0" />
	</ItemGroup>
</Project>